version: '3.8'

services:

  user-service:
    build: ./user-service
    container_name: user-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=${MONGO_URI}/users_db?retryWrites=true&w=majority&appName=project
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
    networks:
      - microservices-network

  song-service:
    build: ./song-service
    container_name: song-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGODB_URI=${MONGO_URI}/songs_db?retryWrites=true&w=majority&appName=project
      - REDIS_URL=${REDIS_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - USER_SERVICE_URL=http://user-service:3001
      - ALBUM_SERVICE_URL=http://album-service:3003
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - RECOMBEE_DATABASE_ID=${RECOMBEE_DATABASE_ID}
      - RECOMBEE_PRIVATE_TOKEN=${RECOMBEE_PRIVATE_TOKEN}
      - RECOMBEE_REGION=${RECOMBEE_REGION}
    depends_on:
      - user-service
    networks:
      - microservices-network

  album-service:
    build: ./album-service
    container_name: album-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGODB_URI=${MONGO_URI}/albums_db?retryWrites=true&w=majority&appName=project
      - REDIS_URL=${REDIS_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - USER_SERVICE_URL=http://user-service:3001
      - SONG_SERVICE_URL=http://song-service:3002
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
    depends_on:
      - user-service
      - song-service
    networks:
      - microservices-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - USER_SERVICE_URL=http://user-service:3001
      - SONG_SERVICE_URL=http://song-service:3002
      - ALBUM_SERVICE_URL=http://album-service:3003
    depends_on:
      - user-service
      - song-service
      - album-service
    networks:
      - microservices-network

volumes:
  mongo_data:

networks:
  microservices-network:
    driver: bridge